version: 0.2

phases:
  install:
    commands:
      - yum install -y jq
  build:
    commands:
      - ami_id=$(aws ssm get-parameter --name "ami_id" --query Parameter.Value | tr -d '"')
      - echo "Using AMI ID: $ami_id"

      - |
        aws ec2 create-launch-template-version \
          --launch-template-id lt-xxxxxxxxxxxxxxxxx \
          --launch-template-data '{
            "ImageId": "'$ami_id'",
            "InstanceType": "t3.micro",
            "KeyName": "your-keypair",
            "SecurityGroupIds": ["sg-xxxxxxxxxxxxx"]
          }'

      - latest=$(aws ec2 describe-launch-templates --launch-template-ids lt-xxxxxxxxxxxxxxxxx | jq -r '.LaunchTemplates[].LatestVersionNumber')
      - aws ec2 modify-launch-template --launch-template-id lt-xxxxxxxxxxxxxxxxx --default-version $latest

      - aws autoscaling start-instance-refresh --auto-scaling-group-name your-asg-name
